"""
Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
SPDX-License-Identifier: MIT-0
"""

from test.unit.rules import BaseRuleTestCase

from cfnlint.runner import TemplateRunner
from cfnlint.rules.conditions.Used import Used  # pylint: disable=E0401


class TestUsedConditionsCfnLint002(BaseRuleTestCase):
    """Verify all conditions generated by the CFNLINT-002 reproduction."""

    def setUp(self):
        """Run W8001 against the transformed reproduction."""
        super().setUp()
        self.collection.register(Used())
        runner = TemplateRunner("", self._template(), self.config, self.collection)
        self.matches = list(runner.run())
        self.resource_conditions = {
            resource["Condition"]
            for resource in runner.cfn.get_resources().values()
        }

    @staticmethod
    def _template():
        return {
            "Transform": "AWS::LanguageExtensions",
            "Mappings": {
                "BucketConfiguration": {
                    "Default": {
                        "BucketNames": ["Bucket1", "Bucket2", "Bucket3"]
                    }
                }
            },
            "Conditions": {
                "ShouldCreateBucket1": {"Fn::Equals": ["a", "a"]},
                "ShouldCreateBucket2": {"Fn::Equals": ["a", "a"]},
                "ShouldCreateBucket3": {"Fn::Equals": ["a", "a"]},
                "UnrelatedCondition": {"Fn::Equals": ["a", "a"]},
            },
            "Resources": {
                "Fn::ForEach::Configurations": [
                    "Configuration",
                    ["Default"],
                    {
                        "Fn::ForEach::Buckets": [
                            "BucketName",
                            {
                                "Fn::FindInMap": [
                                    "BucketConfiguration",
                                    {"Ref": "Configuration"},
                                    "BucketNames",
                                ]
                            },
                            {
                                "${BucketName}Resource": {
                                    "Type": "AWS::S3::Bucket",
                                    "Condition": {
                                        "Fn::Sub": "ShouldCreate${BucketName}"
                                    },
                                }
                            },
                        ]
                    },
                ]
            },
        }

    def _assert_generated_condition_is_used(self, condition):
        self.assertIn(condition, self.resource_conditions)
        self.assertNotIn(
            ["Conditions", condition],
            [match.path for match in self.matches],
        )
        self.assertEqual(
            [["Conditions", "UnrelatedCondition"]],
            [match.path for match in self.matches],
        )

    def test_cfnlint_002_nested_foreach_findinmap_sub_emits_no_w8001_for_bucket1(
        self,
    ):
        """GUID: CFNLINT-002 - ShouldCreateBucket1 receives no W8001."""
        self._assert_generated_condition_is_used("ShouldCreateBucket1")

    def test_cfnlint_002_nested_foreach_findinmap_sub_emits_no_w8001_for_bucket2(
        self,
    ):
        """GUID: CFNLINT-002 - ShouldCreateBucket2 receives no W8001."""
        self._assert_generated_condition_is_used("ShouldCreateBucket2")

    def test_cfnlint_002_nested_foreach_findinmap_sub_emits_no_w8001_for_bucket3(
        self,
    ):
        """GUID: CFNLINT-002 - ShouldCreateBucket3 receives no W8001."""
        self._assert_generated_condition_is_used("ShouldCreateBucket3")
